name: frent_jogja
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.6.2
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.6.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  intl: ^0.17.0
  lottie: ^1.3.0
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/frent-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
